#!/usr/bin/env python
"""Command line interface to Verso"""

import logging
import click
from core.logic import Logic

@click.group()
def cli():
    """Verso.

    This application provides functionality for managing versioning.

    """
    logging.basicConfig(level=logging.INFO)

@cli.command("current-version")
def current_version():
    """Identify the current version of the project."""
    logic = Logic()
    logic.get_current_version()

@cli.command("next-version")
def next_version():
    """Identify the next version of the project.

    The next version is rather the next _generated_ version of the
    project. If the current version is say 0.1.2, then the next
    version is 0.1.3.

    """
    logic = Logic()
    logic.get_next_version()

if __name__ == '__main__':
    cli()
